# Generated by Django 5.1.1 on 2024-10-29 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('history_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('use_case_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UseCaseSpecification',
            fields=[
                ('specification_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('specification_name', models.CharField(max_length=30)),
                ('exceptions_path', models.TextField()),
                ('preconditions', models.TextField()),
                ('postconditions', models.TextField()),
                ('basic_path', models.TextField()),
                ('alternative_path', models.TextField()),
                ('specification_desc', models.TextField()),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usecase.usecase')),
            ],
        ),
    ]
