# Generated by Django 5.1.1 on 2024-10-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=255)),
                ('feature_name', models.CharField(max_length=255)),
            ],
        ),
    ]
