# Generated by Django 5.1.1 on 2024-11-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0002_actorfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case_name', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('summary_description', models.TextField()),
                ('pre_conditions', models.TextField()),
                ('post_conditions', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='usecase',
            old_name='title',
            new_name='nama',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='user',
        ),
        migrations.CreateModel(
            name='ExceptionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_step', models.TextField()),
                ('system_step', models.TextField()),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_paths', to='usecase.specification')),
            ],
        ),
        migrations.CreateModel(
            name='BasicPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_step', models.TextField()),
                ('system_step', models.TextField()),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_paths', to='usecase.specification')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_step', models.TextField()),
                ('system_step', models.TextField()),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_paths', to='usecase.specification')),
            ],
        ),
        migrations.DeleteModel(
            name='UseCaseSpecification',
        ),
    ]
