# Generated by Django 5.1.1 on 2024-11-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0003_specification_rename_title_usecase_nama_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCaseSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case_name', models.CharField(max_length=255)),
                ('actor', models.CharField(default=1, max_length=255)),
                ('summary_description', models.TextField()),
                ('pre_conditions', models.TextField()),
                ('post_conditions', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='alternativepath',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_paths', to='usecase.usecasespecification'),
        ),
        migrations.AlterField(
            model_name='basicpath',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_paths', to='usecase.usecasespecification'),
        ),
        migrations.AlterField(
            model_name='exceptionpath',
            name='use_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_paths', to='usecase.usecasespecification'),
        ),
        migrations.DeleteModel(
            name='Specification',
        ),
    ]
