# Generated by Django 5.1.1 on 2024-11-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0005_remove_basicpath_use_case_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecasespecification',
            old_name='postconditions',
            new_name='post_conditions',
        ),
        migrations.RenameField(
            model_name='usecasespecification',
            old_name='preconditions',
            new_name='pre_conditions',
        ),
        migrations.RenameField(
            model_name='usecasespecification',
            old_name='specification_desc',
            new_name='summary_description',
        ),
        migrations.RemoveField(
            model_name='usecasespecification',
            name='specification_name',
        ),
        migrations.RemoveField(
            model_name='usecasespecification',
            name='use_case',
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='actor',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='use_case_name',
            field=models.CharField(default=1234, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usecasespecification',
            name='specification_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
