# Generated by Django 5.1.1 on 2024-11-06 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0006_rename_postconditions_usecasespecification_post_conditions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_step', models.TextField(blank=True, null=True)),
                ('system_step', models.TextField(blank=True, null=True)),
                ('use_case_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_paths', to='usecase.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='BasicPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_step', models.TextField(blank=True, null=True)),
                ('system_step', models.TextField(blank=True, null=True)),
                ('use_case_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_paths', to='usecase.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_step', models.TextField(blank=True, null=True)),
                ('system_step', models.TextField(blank=True, null=True)),
                ('use_case_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_paths', to='usecase.usecasespecification')),
            ],
        ),
        migrations.DeleteModel(
            name='Path',
        ),
    ]
