# Generated by Django 5.1.1 on 2024-11-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecase', '0007_alternativepath_basicpath_exceptionpath_delete_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternativepath',
            old_name='actor_step',
            new_name='alternative_actor_step',
        ),
        migrations.RenameField(
            model_name='alternativepath',
            old_name='system_step',
            new_name='alternative_system_step',
        ),
        migrations.RenameField(
            model_name='basicpath',
            old_name='actor_step',
            new_name='basic_actor_step',
        ),
        migrations.RenameField(
            model_name='basicpath',
            old_name='system_step',
            new_name='basic_system_step',
        ),
        migrations.RenameField(
            model_name='exceptionpath',
            old_name='actor_step',
            new_name='exception_actor_step',
        ),
        migrations.RenameField(
            model_name='exceptionpath',
            old_name='system_step',
            new_name='exception_system_step',
        ),
    ]
